apiVersion: apps/v1 # argoproj.io/v1alpha1 # apps/v1
kind: Deployment # Rollout # Deployment
metadata:
  name: helloworld-deploy
  labels:
    app: helloworld
spec:
  replicas: 5
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
          app: helloworld
    spec:
      containers:
        - name: helloworld
          image: argoproj/rollouts-demo:blue
          imagePullPolicy: Always
          ports:
          - name: front
            containerPort: 80