apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 5
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
          app: helloworld
    spec:
      containers:
        - name: helloworld
          image: samuelblin/helloworld:1.0
          imagePullPolicy: Always
          ports:
          - name: front
            containerPort: 80